### ISSUE TITLE
`install.sh` will delete `/usr/loca/bin` if there exists a `vimana`

### ISSUE THREAD

**Issue by breeze2501** [Vistara-Labs/vimana#9]
<img width="338" alt="Screen Shot 2023-12-05 at 09 54 12" src="https://github.com/Vistara-Labs/vimana/assets/5365604/8aab5d2a-d107-49ac-9168-424badc9b6a9">

I had installed `vimana` and I also deliberately installed `brew`, which was also under `/usr/local/bin`.

Then I rerun the `install.sh`.

<img width="897" alt="Screen Shot 2023-12-05 at 09 54 22" src="https://github.com/Vistara-Labs/vimana/assets/5365604/e820c53e-e606-4499-b10f-40d9c87f412e">

We can see that the script not only reinstall the binary `vimana`. It also deleted the binary file `brew`. Deleting files not expected to be removed violates the safety of users` system.

**Comment by mmchougule** [comment]
fix PR #8 merged, closing this.
